Android enhancement article
bounswe/bounswe2019group4 pull request #364
Opened 2019-12-14 11:20 UTC by EmreDemircioglu

article edit, delete and  rate features implemented

2019-12-14 11:43 UTC, baturalp-yoruk approved these changes

2019-12-15 11:25 UTC, leventbass approved these changes

2019-12-15 11:34 UTC, elif-caliskan requested changes
From profile page we cannot go to article page in menu
and from article page, we have to press back to select from menu again. 
Besides these little changes I think it works nice. Thank you for your work :)

2019-12-15 12:25 UTC, EmreDemircioglu commented
requested changes are implemented

2019-12-15 12:29 UTC, elif-caliskan approved these changes
Thank you for changes :)

2019-12-15 12:29 UTC, merged